# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20181210_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configcontent',
            options={'verbose_name_plural': '09配置文件内容'},
        ),
        migrations.AlterModelOptions(
            name='configtype',
            options={'verbose_name_plural': '08配置文件类型'},
        ),
        migrations.AlterModelOptions(
            name='errorlog',
            options={'verbose_name_plural': '07错误日志表'},
        ),
        migrations.RenameField(
            model_name='configcontent',
            old_name='environment',
            new_name='environment_id',
        ),
        migrations.RenameField(
            model_name='configcontent',
            old_name='publish_status',
            new_name='publish_status_id',
        ),
    ]
