# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20181210_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcontent',
            name='change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.UserProfile', verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='configcontent',
            name='latest_date',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='configtype',
            name='notes',
            field=models.TextField(verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='configtype',
            name='title',
            field=models.CharField(max_length=64, verbose_name='配置类型名'),
        ),
    ]
