# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20181210_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcontent',
            name='latest_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
    ]
