# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20181210_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontent',
            name='users',
            field=models.ManyToManyField(to='repository.Configtype', verbose_name='修改关联'),
        ),
        migrations.AddField(
            model_name='configtype',
            name='allocation',
            field=models.CharField(max_length=64, null=True, verbose_name='配置1'),
        ),
        migrations.AlterField(
            model_name='configcontent',
            name='content',
            field=models.TextField(help_text='例如：证书key-crt-url-字典形式存放', verbose_name='配置内容'),
        ),
        migrations.AlterField(
            model_name='configcontent',
            name='environment_id',
            field=models.IntegerField(choices=[(1, '正式'), (2, '测试')], default=1, verbose_name='当前环境'),
        ),
        migrations.AlterField(
            model_name='configcontent',
            name='publish_status_id',
            field=models.IntegerField(choices=[(1, '存活'), (2, '失效')], default=1, verbose_name='配置文件状态'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(to='repository.UserProfile', verbose_name='用户'),
        ),
    ]
