# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20181212_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configcontent',
            old_name='users',
            new_name='configrelation',
        ),
    ]
