# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20181212_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcontent',
            name='content',
            field=models.TextField(verbose_name='配置内容'),
        ),
        migrations.AlterField(
            model_name='configtype',
            name='allocation',
            field=models.TextField(help_text='例如：证书key-crt-url-字典形式存放', null=True, verbose_name='对应配置'),
        ),
    ]
