# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20181212_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontent',
            name='publish_id',
            field=models.IntegerField(choices=[(1, '发布'), (2, '不发布')], default=2, verbose_name='配置文件状态'),
        ),
    ]
