# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_configcontent_publish_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontent',
            name='action',
            field=models.TextField(null=True, verbose_name='指定动作'),
        ),
        migrations.AlterField(
            model_name='configcontent',
            name='publish_id',
            field=models.IntegerField(choices=[(1, '发布'), (2, '不发布')], default=2, verbose_name='是否发布'),
        ),
    ]
