# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20181212_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configcenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_id', models.IntegerField(choices=[(1, '发布'), (2, '不发布')], default=2, verbose_name='是否发布')),
                ('title', models.CharField(max_length=64, verbose_name='配置名')),
                ('content', models.TextField(verbose_name='配置内容')),
                ('notes', models.TextField(verbose_name='备注')),
                ('conftype_id', models.IntegerField(choices=[(1, '未配置'), (2, 'configmaps'), (3, 'ingresses')], default=1, verbose_name='配置文件类型')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('latest_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('publish_status_id', models.IntegerField(choices=[(1, '存活'), (2, '失效')], default=1, verbose_name='配置文件状态')),
                ('environment_id', models.IntegerField(choices=[(1, '正式'), (2, '测试')], default=1, verbose_name='当前环境')),
                ('change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.UserProfile', verbose_name='修改人')),
            ],
            options={
                'verbose_name_plural': '09配置文件内容',
            },
        ),
        migrations.RenameModel(
            old_name='Configtype',
            new_name='SelfConfig',
        ),
        migrations.RemoveField(
            model_name='configcontent',
            name='change_user',
        ),
        migrations.RemoveField(
            model_name='configcontent',
            name='configrelation',
        ),
        migrations.DeleteModel(
            name='Configcontent',
        ),
        migrations.AddField(
            model_name='configcenter',
            name='configrelation',
            field=models.ManyToManyField(to='repository.SelfConfig', verbose_name='关联操作'),
        ),
    ]
