# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Host',
        ),
    ]
