# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_delete_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=60, verbose_name='主机名')),
                ('i_ip', models.CharField(max_length=30, verbose_name='内网IP')),
                ('o_ip', models.CharField(max_length=30, verbose_name='外网IP')),
                ('cpu_info', models.CharField(max_length=30, verbose_name='CPU')),
                ('mem_info', models.CharField(max_length=30, verbose_name='内存')),
                ('disk_info', models.CharField(max_length=30, verbose_name='磁盘')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.IntegerField(choices=[(1, '存活'), (2, '失效')], null=True, verbose_name='主机状态')),
                ('remarks', models.CharField(max_length=200, null=True, verbose_name='备注')),
                ('instanceid', models.CharField(max_length=30, null=True, verbose_name='标识')),
            ],
        ),
    ]
